// Next
import type { NextPage, NextPageContext } from 'next';
import Head from 'next/head';

// axios
import axios from 'axios';

interface IProps {
  parkData: any;
}

const ParkPage: NextPage<IProps> = ({ parkData }) => {
  console.log(parkData);

  return (
    <>
      <Head>
        <title>Outdoor Adventures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Park Page</h1>
      </div>
    </>
  );
};

export async function getServerSideProps(context: NextPageContext) {
  const parkCode = context.query.parkcode;

  if (typeof parkCode !== 'string') {
    return;
  }

  try {
    const { data } = await axios.get(
      `https://developer.nps.gov/api/v1/parks?parkCode=${parkCode}&api_key=${process.env.NATIONAL_PARKS_APIKEY}`,
    );

    return {
      props: {
        parkData: data,
      }, // will be passed to the page component as props
    };
  } catch (err) {
    return {
      props: {
        parkData: null,
      }, // will be passed to the page component as props
    };
  }
}

// # const { data } = await axios.get(
//   #   `https://developer.nps.gov/api/v1/parks?parkCode=${parkCode}&api_key=${process.env.NATIONAL_PARKS_APIKEY}`,
//   # );
export default ParkPage;
