// React
import React from 'react';

// Next
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Outdoor Adventures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed h-full w-full">
        <Image
          alt=""
          layout="fill"
          objectFit="cover"
          className="fixed h-full w-full"
          src="/images/mountainForestMin.jpg"
        />
      </div>

      <main className="relative z-10 min-h-screen flex items-center justify-center">
        <div className="bg-slate-50/90 text-center max-w-2xl p-4 rounded-lg">
          <h1 className="text-4xl mb-4">Outdoor Adventures</h1>
          <p className="font-light mb-4">
            Welcome to outdoor adventures, your guide to the national parks in the United States. Easily search all
            national parks and look up specific information on each to help you plan your next adventure.
          </p>
          <Link passHref href="/parks">
            <a className="inline-block text-gray-900 hover:text-white border border-gray-800 hover:bg-gray-900 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
              Search Parks
            </a>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
